### ISSUE TITLE
Drop MPI identifiers are limited to 30 characters

### ISSUE THREAD

**Issue by cblaas** [mpi-forum/mpi-issues#403]
# Problem

The name-length limit is no longer true in MPI-4.0:

MPI-4.0-RC 10:9-10:
MPI identifiers are limited to 30 characters (31 with the profiling interface). This is done to avoid exceeding the limit on some compilation systems.

# Proposal

As discussed at the RCM forum meeting in December 2020, we'll drop these two sentences in the Terms Chapter 2 and do the corresponding changes in Chapter 18 Backward Incompatibilities, Chapter 19 Language Bindings and in the Annex B Change-Log.

# References

This issue became obvious during the Terms Chapter RC Review #335, but since it affects 4 Chapters of the standard it should be in a separate issue.

It is also discussed in Backward Incompatibilities Chapter RC Review Issues #358 and in Change-log Chapter RC Review Issues #359.

References to the appropriate PR's see at Todo.

# Todo

- [x] **merged** Dec 18, 2020 --> PR 432: https://github.com/mpi-forum/mpi-standard/pull/432 --> Chapter 2: Remove the two sentences.
- [x] **merged** Dec 18, 2020 --> PR 434: https://github.com/mpi-forum/mpi-standard/pull/434 Commit-2 --> Chapter 18: Add corresponding text. (see also discussion in issues #358 -with Rolf's suggested text- and #359 and latest pdf on #405)
- [x] **merged** Dec 18, 2020 --> PR 434: https://github.com/mpi-forum/mpi-standard/pull/434 Commit-1 -->Chapter 19.1.5: Correct text that's currently there in the MPI-4.0-RC 789:44-45. (see also discussion in issues #358 and #359 and latest pdf on #405)
- [x] **merged** Dec 18, 2020 --> PR 434: https://github.com/mpi-forum/mpi-standard/pull/434 Commit-1 --> Annex B: Add corresponding text. (see also discussion in issues #358 and #359 and latest pdf on #405)

**Comment by cblaas** [comment]
### Other options -not adopted, but discussed- during the RCM:

* Decide whether there is still a need for this name-length limit (no not really, see above):
If the length limit would still make sense, we would keep the sentences and shorten the names (big count, tools, sessions, and Fortran specific routine names).

* The MPI Forum definitely did not like the suggested change of @RolfRabenseifner (see below).


### This problem was found by several persons of the CC and by both RC reviewers that were assigned to these pages ( @abouteiller and @RolfRabenseifner):


**Comments on the RC from @abouteiller (copied from #335):**

**pdf 50, chap 2.2, pp 10:9**
Need to verify if statement “MPI identifiers are limited to 30 characters)” is still valid. We may have spilled over with the large count variants and some session procedure names.


**Comments on the RC from @RolfRabenseifner (copied from #335):**

**Chap 2.2, pp 10:9**
As already mentioned by @abouteiller, we have a problem with the 30 character procedure name limit
(only routines without MPI_T_...):

32 = MPI_INTERCOMM_CREATE_FROM_GROUPS (MPI 4.0 routine with more than 30 characters, no ..._c)
31 = MPI_T_EVENT_SET_DROPPED_HANDLER (T routine with more than 30 characters)
31 = MPI_DATAREP_CONVERSION_FUNCTION
This one and MPI_USER_FUNCTION are not MPI procedures
--> wrong formatting macro on pp 693:1 and 827:27-28 and 23:13
30 = MPI_TYPE_CREATE_HINDEXED_BLOCK (32 = ..._c)
30 = MPI_DIST_GRAPH_NEIGHBORS_COUNT (no ..._c)
30 = MPI_DIST_GRAPH_CREATE_ADJACENT (no ..._c)
29 = MPI_TYPE_CREATE_INDEXED_BLOCK, 31= ..._c
29 = MPI_SESSION_CREATE_ERRHANDLER (no ..._c)
29 = MPI_REDUCE_SCATTER_BLOCK_INIT, 31 = ..._c (with buffer)
28 = MPI_WIN_ALLOCATE_SHARED_CPTR (only old Fortran, no ..._c)
28 = MPI_NEIGHBOR_ALLGATHERV_INIT, 30 = ..._c (with buffer)
28 = MPI_FILE_WRITE_ORDERED_BEGIN
28 = MPI_FILE_GET_POSITION_SHARED

see also rc-40-procedure-names_sorted.txt

Note that for the fortran interfaces upto 4 respectively 6 additional characters are needed if the routine has not or has a buffer,
and plus 1 character for PMPI, see Sect 19.1.5, pp 789:44-45:

> The longest specific procedure names are PMPI_Dist_graph_create_adjacent_f08 and PMPI_File_write_ordered_begin_f08ts both with 35 characters in the mpi_f08 module.

This is no longer correct:
PMPI_Reduce_scatter_block_init_c_f08ts (1+29+2+6=38)
PMPI_Neighbor_allgatherv_init_c_f08ts (1+28+2+6=37)
PMPI_Type_create_hindexed_block_c_f08 (1+30+2+4=37)
PMPI_Intercomm_create_from_groups_f08 (1+32+4=37)
are longer.

Correct is now:

> Longest specific procedure names are, e.g., PMPI_Dist_graph_create_adjacent_f08 and PMPI_File_write_ordered_begin_f08ts both with 35, PMPI_Intercomm_create_from_groups_f08, PMPI_Type_create_hindexed_block_c_f08, and PMPI_Neighbor_allgatherv_init_c_f08ts with 37, and PMPI_Reduce_scatter_block_init_c_f08ts with 38 characters in the mpi_f08 module.

p10:9-10 reads

> MPI identifiers are limited to 30 characters (31 with the proling interface). This is done to avoid exceeding the limit on some compilation systems.

but should read

> MPI identifiers are limited to 32 characters (33 with the proling interface). This is done to avoid exceeding the limit on some compilation systems.

Both, the change in 2.1 and the change in 19.1.5 should be mentioned in a change-log.


**Comments on the RC from @RolfRabenseifner (copied from #335):**

The names problem is even harder: In some new constants and callback prototypes and one existing MPI-3.1 callback prototype, the 25 year old limit of 30 characters for any MPI names is violated:

Constants
34 = MPI_T_CB_REQUIRE_ASYNC_SIGNAL_SAFE
31 = MPI_T_CB_REQUIRE_MPI_RESTRICTED

Callback prototypes
31 = MPI_Session_errhandler_function
31 = MPI_Datarep_conversion_function (already in MPI-2.0)
33 = MPI_Datarep_conversion_function_c

I would recommend to substitute Chap 2 Terms, page 10, lines 9-10

> MPI identifiers are limited to 30 characters (31 with the profiling interface). This is done to avoid exceeding the limit on some compilation systems.

by

> MPI identifiers are limited to 32 characters (35 with the profiling and large count interfaces, and Fortran specific names upto 41). This is done to avoid exceeding the limit on some compilation systems.

This would only require that MPI_T_CB_REQUIRE_ASYNC_SIGNAL_SAFE (=34) is truncated to e.g. MPI_T_CB_REQUIRE_ASYNC_SIG_SAFE (=31).

Section 18.1 Backward Incompatibilities since MPI-3.1, page 777 line 22 add:

> The limit for MPI identifiers was extended from 30 to 32 characters, for specific function names in C from 31 to 35 (with the profiling and large count interfaces), and Fortran specific names from 35 to 41 (in MPI-4.0, the longest specific procedure name in Fortran is smaller than this limit).

Section 19.1.5 page 789, lines read

> The longest specific procedure names are PMPI_Dist_graph_create_adjacent_f08 and
PMPI_File_write_ordered_begin_f08ts both with 35 characters in the mpi_f08 module.

but should read

> The longest specific procedure names is PMPI_Reduce_scatter_block_init_c_f08ts with 38 characters in the mpi_f08 module.

Annex B.1.2 Change-log, page 1031, line 40 add:

> Sections 2.2, 18.1., and 19.1.5 on pages 9, 777, and 786.
The limit for MPI identifiers and the limit for specific function names in C and Fortran was
extended. This change is not backward compatible.
